WITH 
QUERY1 AS 
(SELECT NOMBRE AS NOMBRE, DOCUMENTO AS DOCUMENTO, TIPODOCUMENTO AS TIPODOCUMENTO
FROM USUARIO),

QUERY2 AS
(SELECT ID AS IDEMPRESA
FROM EMPRESA),

QUERY3 AS
(SELECT ID AS IDCONTRATO, ID_CLIENTE AS IDCLIENTE
FROM CONTRATO),

QUERY4 AS
(SELECT ID_CONTRATO AS IDCONTRATO, ID_HABITACION AS IDHABITACION
FROM CONTRATOHABITACION),

QUERY5 AS
(SELECT ID_CONTRATO AS IDCONTRATO, ID_VIVIENDA AS IDVIVIENDA
FROM CONTRATOVIVIENDA),

QUERY6 AS
(SELECT NOMBRE AS NOMBRE, DOCUMENTO AS DOCUMENTO
FROM OPERADOR),

QUERY7 AS 
(SELECT ID AS IDHABITACION
FROM OPERADORHABITACION)

SELECT QUERY1.DOCUMENTO, QUERY4.IDHABITACION, QUERY6.NOMBRE
FROM QUERY1, QUERY2, QUERY3, QUERY4, QUERY6, QUERY7
WHERE QUERY3.IDCLIENTE = QUERY1.DOCUMENTO AND QUERY6.DOCUMENTO = QUERY2.IDEMPRESA AND QUERY4.IDHABITACION = QUERY7.IDHABITACION
GROUP BY QUERY1.DOCUMENTO, QUERY4.IDHABITACION, QUERY6.NOMBRE
ORDER BY QUERY1.DOCUMENTO
;
