WITH Q1 AS(SELECT ID_VIVIENDA AS id, COUNT(ID_VIVIENDA) as cuenta 
FROM CONTRATO 
GROUP BY ID_VIVIENDA 
order by COUNT(ID_VIVIENDA) DESC) 
SELECT  *  FROM q1 INNER JOIN contrato ON contrato.ID=q1.id where rownum<=20;