CREATE TABLE CONTRATO (
ID INTEGER NOT NULL,
FECHAINICIO VARCHAR(30) NOT NULL,
FECHAFIN VARCHAR(30) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
COSTO DECIMAL NOT NULL,
ID_CLIENTE VARCHAR(30) NOT NULL,
ID_VIVIENDA INTEGER,
ID_HABITACION INTEGER,
NUMEROPERSONAS INTEGER,
FECHACREACION VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES USUARIO(DOCUMENTO);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_VIVIENDA2
FOREIGN KEY(ID_VIVIENDA)
REFERENCES VIVIENDA(ID);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_HABITACION2
FOREIGN KEY(ID_HABITACION)
REFERENCES HABITACION(ID);

drop table serviciovivienda;





CREATE TABLE SERVICIOHABITACION(
IDSERVICIO INTEGER NOT NULL,
ID_HABITACION INTEGER,
COSTO DECIMAL,
PRIMARY KEY (IDSERVICIO, id_habitacion)
);


ALTER TABLE SERVICIOHABITACION
ADD CONSTRAINT FK_ID_SERVICIO
FOREIGN KEY(IDSERVICIO)
REFERENCES SERVICIO(ID);


ALTER TABLE SERVICIOHABITACION
ADD CONSTRAINT FK_ID_HABITACIONSERVICIO
FOREIGN KEY(ID_HABITACION)
REFERENCES HABITACION(ID);

drop table tipohabitacion;

rollback;
commit;


CREATE TABLE SERVICIOVIVIENDA(
IDSERVICIO INTEGER NOT NULL,
ID_VIVIENDA INTEGER NOT NULL,
COSTO DECIMAL,
PRIMARY KEY (IDSERVICIO, id_vivienda)
);

ALTER TABLE SERVICIOVIVIENDA
ADD CONSTRAINT FK_ID_SERVICIOVIVIENDA
FOREIGN KEY(IDSERVICIO)
REFERENCES SERVICIO(ID);


ALTER TABLE SERVICIOVIVIENDA
ADD CONSTRAINT FK_ID_VIVIENDAYSERVICIO
FOREIGN KEY(ID_VIVIENDA)
REFERENCES VIVIENDA(ID);



drop table tipohabitacion;

CREATE TABLE TIPOHABITACION(
ID INTEGER NOT NULL,
TIPO VARCHAR(40) NOT NULL,
PRIMARY KEY (ID, TIPO)
);



ALTER TABLE TIPOHABITACION
ADD CONSTRAINT FK_ID_HABITACION
FOREIGN KEY(ID)
REFERENCES HABITACION(ID);


commit;



CREATE TABLE OPERADORHABITACION(
ID INTEGER NOT NULL,
ID_OPERADOR VARCHAR(50) NOT NULL,
PRIMARY KEY (ID, ID_OPERADOR)
);


ALTER TABLE OPERADORHABITACION
ADD CONSTRAINT FK_ID_EMPRESA
FOREIGN KEY(ID_OPERADOR)
REFERENCES OPERADOR(DOCUMENTO);

ALTER TABLE OPERADORHABITACION
ADD CONSTRAINT FK_ID
FOREIGN KEY(ID)
REFERENCES HABITACION(ID);



insert into servicio
(id, nombre)
values
(25, 'aseo');





CREATE TABLE SERVICIOEMPRESA(
IDSERVICIO INTEGER NOT NULL,
ID_EMPRESA VARCHAR2(30),
COSTO DECIMAL,
PRIMARY KEY (IDSERVICIO, id_empresa)
);


ALTER TABLE SERVICIOEMPRESA
ADD CONSTRAINT FK_ID_SERVICIOEMPRESA
FOREIGN KEY(IDSERVICIO)
REFERENCES SERVICIO(ID);


ALTER TABLE SERVICIOEMPRESA
ADD CONSTRAINT FK_ID_EMPRESAYSERVICIO
FOREIGN KEY(ID_EMPRESA)
REFERENCES EMPRESA(ID);