CREATE TABLE PERSONANATURAL(
DOCUMENTO VARCHAR(30) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
EDAD INTEGER NOT NULL,
GENERO CHAR NOT NULL,
APELLIDO VARCHAR(30),
PRIMARY KEY (DOCUMENTO)
);

ALTER TABLE PERSONANATURAL
ADD CONSTRAINT PERSONA_FK
FOREIGN KEY(DOCUMENTO)
REFERENCES OPERADOR(DOCUMENTO);

