CREATE TABLE HABITACION(
ID INTEGER NOT NULL,
CAPACIDAD INTEGER NOT NULL,
TIPO VARCHAR(30) NOT NULL,
UBICACION VARCHAR(30) NOT NULL,
PRECIO DECIMAL NOT NULL,
ID_EMPRESA VARCHAR(30),
ESCOMPARTIDA CHAR NOT NULL,
ID_PERSONA VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);

ALTER TABLE HABITACION
ADD CONSTRAINT UNIQUE_UBICACION_HABITACION
UNIQUE(UBICACION);

ALTER TABLE HABITACION
ADD CONSTRAINT FK_ID_EMPRESA
FOREIGN KEY(ID_EMPRESA)
REFERENCES EMPRESA(ID);

ALTER TABLE HABITACION
ADD CONSTRAINT FK_ID_PERSONA
FOREIGN KEY(ID_PERSONA)
REFERENCES PERSONANATURAL(DOCUMENTO);