
-----------------Crea la tabla de contrato
CREATE TABLE CONTRATO (
ID INTEGER NOT NULL,
FECHAINICIO VARCHAR(30) NOT NULL,
FECHAFIN VARCHAR(30) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
COSTO DECIMAL NOT NULL,
ID_CLIENTE VARCHAR(30) NOT NULL,
ID_VIVIENDA INTEGER,
ID_HABITACION INTEGER,
NUMEROPERSONAS INTEGER,
FECHACREACION VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES USUARIO(DOCUMENTO);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_VIVIENDA2
FOREIGN KEY(ID_VIVIENDA)
REFERENCES VIVIENDA(ID);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_ID_HABITACION2
FOREIGN KEY(ID_HABITACION)
REFERENCES HABITACION(ID);





