---------------Crear tabla Empresa

CREATE TABLE EMPRESA(
ID VARCHAR(30) NOT NULL,
NUMREGISTROSUPERINTENDENCIA VARCHAR(30) NOT NULL,
NUMREGISTROCAMARADECOMERCIO VARCHAR(30) NOT NULL,
UBICACION VARCHAR(30) NOT NULL,
TIPO VARCHAR(30) NOT NULL, 
HORARIOAPERTURA VARCHAR(30),
HORARIOCIERRE VARCHAR(30),
PRIMARY KEY(ID)
);
---------------Restricciones de ND
ALTER TABLE Empresa
ADD CONSTRAINT UNIQUE_NUMREGSI
UNIQUE(NUMREGISTROSUPERINTENDENCIA );
------------------
ALTER TABLE Empresa
ADD CONSTRAINT UNIQUE_NUMREGCC
UNIQUE(NUMREGISTROCAMARADECOMERCIO);
-------------------
ALTER TABLE Empresa
ADD CONSTRAINT UNIQUE_UBICACION
UNIQUE(UBICACION);

ALTER TABLE EMPRESA
ADD CONSTRAINT ID_FK_EMPRESA
FOREIGN KEY (ID)
REFERENCES OPERADOR(DOCUMENTO);
