-----------------CREA LA TABLA OPERADOR 

CREATE TABLE OPERADOR(
DOCUMENTO VARCHAR(30) NOT NULL,
LOGIN VARCHAR(30) NOT NULL,
CONTRASENHA VARCHAR(30) NOT NULL,
CORREO VARCHAR(30) NOT NULL,
TIPODOCUMENTO VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
PRIMARY KEY (DOCUMENTO),
UNIQUE (LOGIN, CORREO));


